---
# Apply latest Ruby style guide and newly introduced cops
AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - '_snippets/**/*'
  Include:
  - 'Gemfile'
  - 'Rakefile'
  - '**/*.rb'

# ignore block length in test code only
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*'
    - 'Rakefile'

# See: https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Layout/MultilineMethodCallIndentation
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Style/HashSyntax:
  Enabled: true
  Exclude:
    - 'Rakefile'